#=================================================================================================
# fichier  		: conf.properties
# Package       : resources
# Version       : V1.0
#
# Description  : Fichier contenant les différentes données utiles à l'application.
#=================================================================================================
# Données connexion SQLServer
jdbc.driver.class=com.microsoft.sqlserver.jdbc.SQLServerDriver
# jdbc.url=jdbc:sqlserver://127.0.0.1;databaseName=AgImmo
jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=AgImmo;encrypt=true;trustServerCertificate=true


jdbc.login=AdmAgImmo
jdbc.pwd=Azerty1!